version: "3.8"

services:
  db:
    # PostGIS database
    build: ./pgsql/
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=ifcsql
      - POSTGRES_USER=ifcsql
      - POSTGRES_PASSWORD=ifcsql
      - PGDATA=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ifcsql" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ontop:
    image: ontop/ontop:5.0.1
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/IFC4.owl
      #Ontology with an additional data property to get coordinates directly
      #ONTOP_ONTOLOGY_FILE: /opt/ontop/input/IFC4-with-rules.owl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/IFC4.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/IFC4.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/ifc.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_DEBUG: "true"
      #Optional rules file allows for ?site ifc:fullCoordinates ?coord .
      #ONTOP_SPARQL_RULES_FILE: /opt/ontop/input/ifc-rules.toml
    volumes:
      - ./vkg-ifc-mappings:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    depends_on:
      app:
        condition: service_completed_successfully
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "db:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "${MAPPED_ONTOP_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"