version: "3.8"

services:

  db:
    # sample image with Tartu data
    image: albulenpano/3dcitydb:v0
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3dcitydb
      - PGDATA=postgres

  ontop:
    image: ontop/ontop:5.0.1
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/citygml2.0.owl
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_MAPPING_FILE: /opt/ontop/input/citygml2.0.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/citygml2.0.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/citygml2.0.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_DEBUG: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "db:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "${MAPPED_ONTOP_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jena-fuseki:
    build:
      context: ./jena-fuseki
    init: true
    environment:
      #- user is "admin"
      - ADMIN_PASSWORD=enter1234
      - JVM_ARGS=-Xmx24G
      - TDB=2
    volumes:
      - ./wait-for-it:/wait-for-it
    command:
      - "/jena-fuseki/fuseki-server"
    entrypoint:
      [
        "/wait-for-it/wait-for-it.sh",
        "ontop:8080",
        "--timeout=0",
        "--strict",
        "--",
        "/usr/bin/tini",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - "${MAPPED_FUSEKI_PORT}:3030"
    extra_hosts:
      - "host.docker.internal:host-gateway"