title="OSM VKG mini tutorial"

[defaultTab]
query="""
PREFIX lgdo: <http://linkedgeodata.org/ontology/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

# Find all cafe-s in the Tartu city center
SELECT * WHERE {
  ?subject a lgdo:Cafe .
  ?subject geo:asWKT ?geom .
  FILTER(geof:sfIntersects('POLYGON ((26.713717 58.385244, 26.741222 58.385344, 26.742177 58.368919, 26.715818 58.368318, 26.713717 58.385244))'^^geo:wktLiteral, ?geom)) .
}
LIMIT 150
"""

[[tabGroups]]

name="Examples"

[[tabGroups.tabs]]

name="Cafes in Tartu"
query="""
PREFIX lgdo: <http://linkedgeodata.org/ontology/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

# Find all cafe-s in the Tartu city center
SELECT * WHERE {
  ?subject a lgdo:Cafe .
  ?subject geo:asWKT ?geom .
  FILTER(geof:sfIntersects('POLYGON ((26.713717 58.385244, 26.741222 58.385344, 26.742177 58.368919, 26.715818 58.368318, 26.713717 58.385244))'^^geo:wktLiteral, ?geom)) .
}
LIMIT 150
"""

[[tabGroups.tabs]]

name="Restaurants in Tartu"
query="""
PREFIX lgdo: <http://linkedgeodata.org/ontology/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

# Find all cafe-s in the Tartu city center
SELECT * WHERE {
  ?subject a lgdo:Restaurant .
  ?subject geo:asWKT ?geom .
  FILTER(geof:sfIntersects('POLYGON ((26.713717 58.385244, 26.741222 58.385344, 26.742177 58.368919, 26.715818 58.368318, 26.713717 58.385244))'^^geo:wktLiteral, ?geom)) .
}
LIMIT 150
"""