# NOTE: Version 4.3.2 throws errors
FROM eclipse/rdf4j-workbench:4.2.3
USER root
RUN chmod -R 777 logs
RUN chmod -R 777 /usr/local/tomcat/logs
RUN chmod -R +t logs
RUN chmod -R +t /usr/local/tomcat/logs