version: "3.4"

services:
  postgres:
    image: postgis/postgis
    command:
      # See https://osm2pgsql.org/doc/manual.html#tuning-the-postgresql-server
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "work_mem=50MB"
      - "-c"
      - "maintenance_work_mem=4GB"
      - "-c"
      - "autovacuum_work_mem=1GB"
      - "-c"
      - "wal_level=minimal"
      - "-c"
      - "checkpoint_timeout=60min"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "max_wal_senders=0"
      - "-c"
      - "random_page_cost=1.0"
    ports:
      - "7779:5432"
    environment:
      ALLOW_IP_RANGE: "0.0.0.0/0"
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PG_PORT: 7779

  ontop2:
    image: ontop/ontop:5.0.0
    environment:
      ONTOP_DB_USER: docker
      ONTOP_DB_PASSWORD: docker
      ONTOP_DB_URL: jdbc:postgresql://host.docker.internal:7779/docker
      ONTOP_DB_DRIVER: org.postgresql.Driver
      ONTOP_DEV_MODE: "true"
      ONTOP_DEBUG: "true"
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/lgd.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/lgd.obda
      ONTOP_XML_CATALOG_FILE: /opt/ontop/input/catalog-v001.xml
      ONTOP_PORTAL_FILE: /opt/ontop/input/lgd.portal.toml
    volumes:
      - ./vkg-osm:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./vkg-osm/library:/opt/ontop/input/library
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "8082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"